### ISSUE TITLE
Issue with layout

### ISSUE THREAD

**Issue by haroon10725** [mansoormemon/foodies#4]
Broken responsive design.

**Comment by haroon10725** [comment]
![d1](https://user-images.githubusercontent.com/104259212/235497637-9f276c36-5fe4-4f1d-9389-ceacb89692f8.PNG)
![d2](https://user-images.githubusercontent.com/104259212/235497648-6e70060e-3b5f-45d8-85a7-623f75140b7a.PNG)
![d3](https://user-images.githubusercontent.com/104259212/235497661-c5a1a390-792a-4c4e-bcda-eb0de2d14e4e.PNG)
![d4](https://user-images.githubusercontent.com/104259212/235497669-a2e2f3c3-2814-4063-81e4-5c0fe4709f78.PNG)
![d5](https://user-images.githubusercontent.com/104259212/235497680-83d0af4a-ce79-4dfc-bf8c-1e329768af15.PNG)

**Comment by mansoormemon** [comment]
Fixed 8788fa7c60716bb61d39c2087f72a5cb65ab990e

**Comment by mansoormemon** [comment]
![Screenshot from 2023-05-02 00-46-26](https://user-images.githubusercontent.com/60285282/235518876-bb63af4b-f9d7-4959-9dbd-71ceed0bdc00.png)
![Screenshot from 2023-05-02 00-46-22](https://user-images.githubusercontent.com/60285282/235518887-cffec2d5-7956-4fd7-b301-62776f467a85.png)
![Screenshot from 2023-05-02 00-46-19](https://user-images.githubusercontent.com/60285282/235518896-6f51a0de-7bcb-4e9a-889c-7700f16af05f.png)
![Screenshot from 2023-05-02 00-46-04](https://user-images.githubusercontent.com/60285282/235518900-e3518e7e-a160-40cc-bc22-b7626567320a.png)
![Uploading Screenshot from 2023-05-02 00-45-58.png…]()
